
server:
    port: 10821
    tomcat:
        uri-encoding: UTF-8
    servlet:
        encoding:
            charset: UTF-8
            enabled: true
            force: true

spring:
    messages:
        encoding: UTF-8
    jmx:
        enabled: false
    freemarker:
        charset: utf-8
        cache: false
        suffix: .ftl
#        template-loader-path: /page/

javafx:
#    title: 我的javaFx工具集合
    appicons: /static/images/icon.jpg
    stage:
        resizable: true

mutool:
    server:
        domain: http://127.0.0.1
